### ISSUE TITLE
Script doesn't detect when lossless saves more space

### ISSUE THREAD

**Issue by ScottPierce** [colinrtwhite/WebPify#2]
I ran this script over my app yesterday (thanks for the script by the way!), and I found that the script errored a lot because I had a lot of small images that when converted at a reduced quality would end up larger than the optimized `.png`. However, I found that if I converted those same images with the  lossless `.webp` conversion in Android Studio, then I'd save 20-40% off the optimized `.png` size.

It's a bit counter-intuitive, but a LOT of the images in my app had this problem. I just used a combination of webpify, and android studio's convert to `.webp` losslessly feature. It'd be nice if webpify handled it all though.

**Comment by colinrtwhite** [comment]
Hmm I didn't know that using lossless compression could actually out perform lossy compression in certain instances. Do you have an example PNG I could run some tests on?

Thanks for using the script (and finding this issue)!

**Comment by ScottPierce** [comment]
Sure, do you have an email I could send it to? I'd prefer not to post it to
github directly.

**Comment by colinrtwhite** [comment]
Sure, you can email me at colin@colinwhite.me.

**Comment by colinrtwhite** [comment]
@ScottPierce Sorry it took longer than expected to get back to you on this issue. I've just posted a new release which fixes this issue.
